dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://developer.huawei.com/repo/' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url 'https://maven.aliyun.com/repository/google' }
    }
}

include ':TMessagesProj'
include ':TMessagesProj_App'
// include ':TMessagesProj_AppHuawei'
// include ':TMessagesProj_AppHockeyApp'
// include ':TMessagesProj_AppStandalone'
include ':BaseLib'
include ':smart-swipe'
